version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.0
    container_name: elasticsearch
    hostname: elasticsearch
    restart: unless-stopped
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elk_data/es/es_data:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - node.name=node1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms384m -Xmx384m"
      - cluster.initial_master_nodes=node1
    ulimits:
      memlock:
        soft: -1
        hard: -1

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.8.0
    container_name: logstash
    hostname: logstash
    depends_on:
      - elasticsearch
    restart: always
    ports:
      - 5001:5000/udp
      - 5001:5000/tcp
      - 9600:9600
    volumes:
      - ./elk_data/ls/ls_config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro  
      - ./elk_data/ls/ls_data:/usr/share/logstash/data:rw
      - ./elk_data/ls/ls_template:/usr/share/logstash/template:ro
      - ./elk_data/ls/ls_pipeline:/usr/share/logstash/pipeline:ro
      - ./elk_data/ls/ls_scripts:/user_scripts
      #- ./elk_data/ls/ls_logs:/usr/share/logstash/logs:ro
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
    
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.8.0
    container_name: kibana
    hostname: kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      - SERVER_NAME=kibana_server
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
